import { GetContactInformationDto } from "../../contactInformation/dto/getContactInformationDto"
import { GetDepartmentDto } from "../../department/dto/getDepartmetDto"

export interface GetUserOutput {
  id?: number,
  userName?: string,
  name?: string,
  surname?: string,
  emailAddress?: string,
  isActive?: boolean,
  fullName?: string,
  lastLoginTime?: Date,
  creationTime?: Date,
  roleNames?: [string],
  departmentId?: number,
  departmentName?: string,
  companyId?:number,
  userTypeId?: number,
  approvedTypeId?: number,
  contactInformationId: number,
  titleId?: number,
  titleName?: string,
  nationalityCountyId?: number,
  citizenshipNo?: string,
  registerNo?: string,
  gender?: boolean,
  dateOfBirth?: Date,
  placeOfBirth?: string,
  father?: string,
  mother?: string,
  isMarried?: true,
  isMilitaryComplate?: true,
  drivingTime?: Date,
  drivingType?: string,
  payrollCode?: string,
  sosyalSecurityType?: string,
  jobStartDate?: Date,
  educationStatusId?: number,
  bloodTypeId?: number,
  passportNo?: string,
  passportStartDate?: Date,
  passportEndDate?: Date,
  passportPlace?: string,
  passportTypeId?: number,
  passportViseNo?: string,
  passportViseDate?: Date,
  workPermitLastDate?: Date,
  contactInformation?: GetContactInformationDto,
  department?: GetDepartmentDto,
  title?: {}
}
